<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Macro / Keybind Mod</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers-and-time</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keys</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#mod-variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#user-variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#user-variable-use</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#not-script</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#illegal-variable-use</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.double-slash.macro</string>
		</dict>
		<key>directions</key>
		<dict>
			<key>match</key>
			<string>\b(NORTH|SOUTH|EAST|WEST)\b</string>
			<key>name</key>
			<string>constant.language.macro</string>
		</dict>
		<key>illegal</key>
		<dict>
			<key>match</key>
			<string>[^\s}]</string>
			<key>name</key>
			<string>invalid.illegal.macro</string>
		</dict>
		<key>illegal-variable-use</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>%(@|@?(?:&amp;|#))[\w]+(?!%)</string>
					<key>name</key>
					<string>invalid.illegal.macro</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!%)(@|@?(?:&amp;|#))[\w]+%(?!(@|@?(?:&amp;|#)))</string>
					<key>name</key>
					<string>invalid.illegal.macro</string>
				</dict>
			</array>
		</dict>
		<key>keys</key>
		<dict>
			<key>match</key>
			<string>(?i)\bkey[\w]+</string>
			<key>name</key>
			<string>constant.language.macro</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>begin</key>
			<string>(?i)\b([a-z]+)\(?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.macro</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)?;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#numbers-and-time</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keys</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#directions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mod-variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#user-variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#user-variable-use</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal-variable-use</string>
				</dict>
			</array>
		</dict>
		<key>mod-variable</key>
		<dict>
			<key>match</key>
			<string>%[A-Z]+%</string>
			<key>name</key>
			<string>constant.language.macro</string>
		</dict>
		<key>not-script</key>
		<dict>
			<key>begin</key>
			<string>(\}\$\$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.block.begin.macro</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>text.macro</string>
			<key>end</key>
			<string>(\$\$\{)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.block.end.macro</string>
				</dict>
			</dict>
		</dict>
		<key>numbers-and-time</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.macro</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b([0-9]+(t|ms)?)\W</string>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>("|')</string>
			<key>end</key>
			<string>("|')</string>
			<key>name</key>
			<string>string.quoted.macro</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#mod-variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#user-variable-use</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal-variable-use</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(&amp;[a-z0-9])(?&lt;!%)</string>
					<key>name</key>
					<string>markup.heading.macro</string>
				</dict>
			</array>
		</dict>
		<key>user-variable</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.macro</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(@|@?(?:&amp;|#))[\w]+</string>
			<key>name</key>
			<string>variable.other.macro</string>
		</dict>
		<key>user-variable-use</key>
		<dict>
			<key>match</key>
			<string>%(@|@?(?:&amp;|#))[\w]+%</string>
			<key>name</key>
			<string>storage.type.macro</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.macro</string>
	<key>uuid</key>
	<string>b2fafee2-d90b-491c-b931-e3d388fc80f3</string>
</dict>
</plist>
